export enum UIActionsEnum{
    //UI reducer types
    SET_ERRORS='SET_ERRORS',
    SET_LOADING='SET_LOADING',
    CLEAR_LOADING='CLEAR_LOADING',
    CLEAR_ERRORS='CLEAR_ERRORS',
    SET_REDIRECT='SET_REDIRECT',
    CLEAR_REDIRECT='CLEAR_REDIRECT',
    SET_SUCCESS='SET_SUCCESS',
    CLEAR_SUCCESS='CLEAR_SUCCESS'

}